In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
data_yelp=pd.read_csv('/content/251528~3.TXT',sep='\t',header=None)

In [ ]:
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [ ]:
column_name=['Review','Sentiment']
data_yelp.columns=column_name

In [ ]:
data_yelp.shape

(1000, 2)

In [ ]:
data_amazon=pd.read_csv('/content/251528~1.TXT',sep='\t',header=None)

In [ ]:
data_amazon.columns=column_name

In [ ]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [ ]:
data_amazon.shape

(1000, 2)

In [ ]:
data_imdb=pd.read_csv('/content/251528~2.TXT',sep='\t',header=None)

In [ ]:
data_imdb.columns=column_name

In [ ]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [ ]:
data_imdb.shape

(748, 2)

In [ ]:
data=data_yelp.append([data_imdb,data_amazon],ignore_index=True)

In [ ]:
data.shape

(2748, 2)

In [ ]:
data['Sentiment'].value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [ ]:
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

In [ ]:
x=data['Review']
y=data['Sentiment']

Cleaning Data

In [ ]:
import string
punct=string.punctuation
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
from spacy.lang.en.stop_words import STOP_WORDS

In [ ]:
stopwords=list(STOP_WORDS)

In [ ]:
import spacy
nlp=spacy.load(name='en_core_web_sm')

In [ ]:
sentence="Hello all, It's a beautiful dat outside there!"
def text_data_cleaning(sentence):
  doc=nlp(sentence)
  tokens=[]
  for token in doc:
    if token.lemma_ != "-PRON-":
      temp=token.lemma_.lower().strip()
      #print(temp)
    else:
      temp=token.lower_
    tokens.append(temp)
  #return tokens
  cleaned_tokens=[]
  for token in tokens:
    if token not in punct and token not in stopwords: 
      cleaned_tokens.append(token)
    
  return cleaned_tokens  

text_data_cleaning(sentence)    

['hello', 'beautiful', 'dat', 'outside']

Vectorization Feature Engineering (TF-IDF)

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [ ]:
tfidf=TfidfVectorizer(tokenizer=text_data_cleaning)

In [ ]:
Classifier=LinearSVC()


Train the model

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train.shape,x_test.shape

((2198,), (550,))

In [ ]:
x_train.head()

2572                       Awkward to use and unreliable.
526                          And it was way to expensive.
1509    The fat computer geek was unbelievable, the bi...
144     Nice blanket of moz over top but i feel like t...
2483      Provides good protection and looks classy, too.
Name: Review, dtype: object

Fit the x_train and y__train

In [ ]:
clf=Pipeline([('tfidf',tfidf),('clf',Classifier)])

In [ ]:
clf.fit(x_train,y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x7f5a60690710>)),
                ('clf', LinearSVC())])

Predict the Test set results

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


In [ ]:
y_pred=clf.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

array([[210,  73],
       [ 51, 216]])

In [ ]:
accuracy_score(y_test,y_pred)

0.7745454545454545

In [ ]:
clf.predict(["Wow, I am learning Natural Language Processing in fun fashion!"])

array([1])

In [ ]:
clf.predict(["It's hard to learn new things!"])

array([1])